### ISSUE TITLE
search_view_factory does allow to accept view parameters

### ISSUE THREAD

**Issue by levynir** [django-haystack/django-haystack#1063]
The `search_view_factory` method does not allow the user to use it to create subclassed views that receive view parameters in the url

```
    url(r'^(?P<something>.+)?$', search_view_factory(
        view_class=CustomSearchView,
        searchqueryset=sqs
    ), name='search'),
```

```
class CustomSearchView(FacetedSearchView, SearchQueryParser):
    template = "main/pages/search.html"

    def __call__(self, request, something=None):
        self.something = something
        return super(CustomSearchView, self).__call__(request)

```

results in the error

```
Traceback (most recent call last):
  File "...python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
TypeError: search_view() got an unexpected keyword argument 'something'
```

this can be fixed by changing the method like this

```
def search_view_factory(view_class=SearchView, *args, **kwargs):
    '''
    This is a replacement for the original method from haystack.views
    that allows the url() to pass parameters to the view
    '''
    def search_view(request, *vargs, **vkwargs):
        return view_class(*args, **kwargs)(request, *vargs, **vkwargs)
    return search_view
```

**Comment by iXioN** [comment]
+1, 

I got the same error and search_view_factory with args work fine in dev  but I have errors that seems to be caused by threading problems in production. The original search_view_factory seems to be create to avoid this error. 

ImproperlyConfigured: Model '<class 'xxxx'>' has more than one 'SearchIndex`` handling it. Please exclude either '<xxxx object at 0x7ff9bf74cc80>' or '<xxxx object at 0x7ff9bd60d258>' using the 'EXCLUDED_INDEXES' setting defined in 'settings.HAYSTACK_CONNECTIONS

**Comment by levynir** [comment]
This is idle too long and iXioN is probably right about the threads issue. Closing this issue.
