### ISSUE TITLE
App checks are invalid

### ISSUE THREAD

**Issue by dcramer** [django-haystack/django-haystack#1152]
https://github.com/django-haystack/django-haystack/blob/master/haystack/utils/app_loading.py#L14

As an example, raven-python's app name is "raven.contrib.django.raven_compat", so the length checks here will fail hard.

**Comment by dcramer** [comment]
Actually before I place 100% blame on Haystack, let me verify some things. I'm not familiar w/ the code and old name app style *should* be used in standard Django, so this could be a user error.

**Comment by dcramer** [comment]
The root cause is app_loading.load_apps here. Confirmed it's not a user error. I dont have time (or knowledge) to submit a fix, but I imagine this is pretty straight forward.

**Comment by acdha** [comment]
I'm working on a fix in #1153 which handles more than one level of hierarchy and gets ready to jettison the last of that rather elderly code since it's redundant with modern versions of Django.

One note. If I'm reading the docs correctly, it looks like Raven isn't following Django's supported behaviour with the last path component being "django":

https://docs.djangoproject.com/en/1.6/ref/settings/#installed-apps
> The application names (that is, the final dotted part of the path to the module containing models.py) defined in INSTALLED_APPS must be unique. For example, you can’t include both django.contrib.auth and myproject.auth in INSTALLED_APPS.

https://docs.djangoproject.com/en/1.7/ref/settings/#installed-apps
> Application labels — by default the final part of the name — must be unique too. For example, you can’t include both django.contrib.auth and myproject.auth. However, you can relabel an application with a custom configuration that defines a different label.

I'm not sure if this has any meaningful impact now, particularly since Raven doesn't define any models and ``django.models`` doesn't exist.

**Comment by dcramer** [comment]
@acdha we do have a "raven_compat" module that we recommend in our docs, though it's very possible that the behavior changed in newer versions of Django that it now errors out if theres a duplicate label. It does appear that its not being used in this situation which is a bit weird (or the message is wrong).

**Comment by acdha** [comment]
Yeah, I thought there used to be an error message but haven't looked into it more since I wanted to add a test for this situation which is increasingly common now (I believe every Grappelli user also hits it).

**Comment by rhblind** [comment]
Good stuff!
Any chance of seeing this fix in a stable release anytime soon?

**Comment by acdha** [comment]
There's a release candidate on PyPI now:

pip install django-haystack==2.4.0rc1
