### ISSUE TITLE
Search on the basis of value from querystring

### ISSUE THREAD

**Issue by TaqiOfficial** [django-haystack/django-haystack#1166]
I have a page on which `haystack search` is implemented with `solar`, for now when page load the query loads all the data, what I want get when page loads, `get the parameters from query string in URL`, then made a query get data from that parameter, that is stored in a list, then on the whole page, the `search is made to relate` to that `specific data contains in the list`, is what method I need to override default query set?

**Comment by acdha** [comment]
The issue tracker is only for bugs. This would be a good question for the mailing list:

https://groups.google.com/d/forum/django-haystack

The behaviour you're describing is what the standard search view provides. I would suggest starting with http://django-haystack.readthedocs.org/en/v2.3.1/tutorial.html and http://django-haystack.readthedocs.org/en/v2.3.1/views_and_forms.html to learn how to customize that behaviour.

**Comment by LiamK** [comment]
Hi, Chris,

The mailing list has lots of questions, but very few answers!  I think 
if questions were to get answered there it would help keep them off the 
bug tracking list.

I've been using django-haystack for a while, and am now running into 
some issues in trying to improve search results for autocomplete using 
Elasticsearch.  I think it's a simple question.
It has been asked before, back in 2012 (!), but no answer.  So, I'm 
starting to despair of getting an answer now.

If I were to put it in the form of a bug report it would go like this:
qs = SearchQuerySet().filter(content_auto=q).boost('NY', 
1.5).order_by('-_score')


The query above fails to boost the score of results having the string 
'NY'.  In fact, it eliminates results that do not match.
(And really what I want to do is to boost matches on that field in 
general, so not "term" boost but "field" boost. But that also apparently 
fails.)

However, I was reluctant to submit it as a bug, since it may be do to my 
lack of understanding of how it's supposed to work.
https://groups.google.com/forum/#!searchin/django-haystack/autocomplete/django-haystack/yloFMgbkVHA/zt8-Fyb_J5gJ

Best,
Liam
