### ISSUE TITLE
Race condition when running update_index --remove

### ISSUE THREAD

**Issue by diwu1989** [django-haystack/django-haystack#1194]
Check out this line:
https://github.com/django-haystack/django-haystack/blob/master/haystack/management/commands/update_index.py#L281

You are paginating over the search queryset from 1 to N, and at the same time, you're removing stale documents. Let's say that you're on page X, and you removed N documents, when you move forward to the next page X+1, you would have missed N documents that would have been on the next page, but they moved forward because your performed the deletion from the previous page.

I think you should do a pass through to find the document ids that should be removed, and then perform the actual remove afterwards in a separate pass.

**Comment by acdha** [comment]
The code you referenced is old enough that memory usage was a more pressing concern, particularly since some haystack users have things like UUIDs instead of integer keys. The two-pass approach is probably sufficient but I'm wondering whether some users regularly delete enough records that it'd be better to reset the step to start at the first deleted record after we process all of the removes for a block so we never have more than one block in memory at a time.

One other note which comes to mind is that I don't see enough benefit to using workers for removes – unlike the indexing, there's no substantial overhead on our side for deleting a record and it'd simplify the code not to have the extra path.

The code which I use in production loads everything into sets so it can efficiently determine all of the pks which need to be added or removed from the index, which is fine since the number of records & size of keys is well within the server memory budget:

https://gist.github.com/acdha/08d0a760221184bd84cf#file-sync_index-py-L82-L83

**Comment by diwu1989** [comment]
Agree that using multiple worker is not worth the extra effort.

If you want to save memory, you can do:
- grab a page of documents from search index order_by document identifier
- ask ORM for `.filter(pk__in=pk_list).values_list('pk', flat=True)` and then find set difference
- take the greatest document identifier of the working set
- repeat with the next page of documents that has identifier greater than the max seen, stop when page is empty

**Comment by pa-jama** [comment]
Whenever I run update_index --remove, it always hangs at the end, no matter how many workers, is that related to this issue?

**Comment by acdha** [comment]
@pa-jama If you're using workers > 1 on old versions of python, potentially. Otherwise it's hard to say without a testcase

**Comment by acdha** [comment]
@diwu1989 I took the simple approach for https://github.com/django-haystack/django-haystack/commit/3c88d41f9a02299d031eef8114dfd4fdc5ed358f because the incremental logic was complicated by the need to deal with running with `commit=False` and I wasn't happy with the amount of complexity that version added to save a modest amount of memory.
