### ISSUE TITLE
contains wrong in elasticsearch backend

### ISSUE THREAD

**Issue by shredding** [django-haystack/django-haystack#1259]
https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L783

Shouldn't this be `contains': u'*%s*',`? 

If not why is `contains` and `exactly` the same?

**Comment by kelvan** [comment]
Took me hours to find this, thanks for the pointer in the right direction, gonna fork haystack for our project.
It seems this is the reason why autocomplete is quite useless with elasticsearch backend in 2.4.1 :(

**Comment by shredding** [comment]
@kelvan : Check this out: https://github.com/django-haystack/django-haystack/issues/1041#issuecomment-149891378

**Comment by acdha** [comment]
@kelvan In particular, I would like feedback on my proposed way to handle backwards compatibility for the `field=` shortcut:

https://github.com/django-haystack/django-haystack/issues/1041#issuecomment-149902911

I could just merge this but since it could potentially affect a fair number of existing users I'd appreciate comments about how it would affect your application.

**Comment by sampeka** [comment]
Closing in favour of #1041
