### ISSUE TITLE
Django 1.9 result.object None

### ISSUE THREAD

**Issue by pulsedemon** [django-haystack/django-haystack#1291]
I know 1.9 isn't fully supported yet, but wanted to bring this up anyway.

I updated to Django 1.9, and haystack 2.4.1 and everything works fine except for result.object returning None.  I wrote some of my own code to manually load the object via the pk in the result and that fixed my problems.

**Comment by sampeka** [comment]
Django 1.9 isn't supported yet, pull in progress here: https://github.com/django-haystack/django-haystack/pull/1277

**Comment by jw** [comment]
The `django.db.model.get_model` is not available any longer, so `None` is returned when calling `django.db.models.get_model`, but in the more recent commit (from the 3rd of January) the `utils.app_loading.py` is used to either use the `django.apps.apps.get_model` when using Django 1.7 or higher, otherwise the old `django.db.models._get_models` is used.

So, best to upgrade to the latest sevelopment version `git+https://github.com/django-haystack/django-haystack.git`.

**Comment by fmarco** [comment]
+1

**Comment by acdha** [comment]
Sorry about the delays but as of 10bcc7668ccaab499f8db516fd59de182aadbcb4 the tests are passing on Django 1.9. If you have any remaining gaps please either rebase against master or close this & open a separate pull request.
