### ISSUE TITLE
Support for Amazon Elasticsearch service connection

### ISSUE THREAD

**Issue by jernsthausen** [django-haystack/django-haystack#1303]
Possible newb issue, but I am hoping to use this in combination with an app deployed on Heroku and would like to use Amazon's Elasticsearch hosting service. I'd also like it to be secured with my IAM credentials.

I don't see an easy way to do this within the settings.py file of my application. It'd be great if support for this were built in. Is there any way to do this, or could it be added?

**Comment by acdha** [comment]
You could definitely implement this in your settings file – if you're using the classic Heroku model where the config info is provided in environmental variables, your settings module can simply pull them in from `os.environ`. If you're doing something like looking up instance-level from EC2 metadata or needs some sort of dynamic lookup, your settings file could make an HTTP request, use boto to look up the endpoints, etc.

I'm not sure this makes sense for Haystack since it would require support and testing but only be relevant to a small percentage of users. If the upstream elasticsearch module was to add some support for this we might want to make sure it's easy to use from Haystack, though.

**Comment by SteveByerly** [comment]
Moving discussion/decision to #1406
