### ISSUE TITLE
How geo spatial search works

### ISSUE THREAD

**Issue by jheld** [django-haystack/django-haystack#1309]
I'm working on a project that requires searching by distance (lat, lon), and I am wondering where the workflow and brains of the search process work.

My assumption is that haystack and elasticsearch (the python library) will serialize to a RESTful request to the elasticsearch node, and that will do the calculation and come back with an object for the library to deserialize.

Given that, why do we require libraries like PostGIS, PROJ, GEOS, GDAL. As in, what are they used for, and why is all of this needed for haystack/django/python? I am using a postgres datastore with elasticsearch hosting the index for the location data.

In terms of scale, I don't like the idea that I have to compile these huge C/C++ libraries every time I spin up a new machine, especially if demand surges.

Perhaps the indexing process is what forces the need for these libraries? As in, they do the calculation during index and then just do reads on it?

**Comment by acdha** [comment]
This would be a good discussion topic for the Google Group: https://groups.google.com/forum/django-haystack

The short answer to your question is that they're not used by Haystack directly but are dependencies if you've chosen to install and use GeoDjango. If you're not otherwise using it and have a way to load your data into the search engine without using that toolchain you should be able to avoid installing them. The only documented dependency in Haystack is an optional geopy dependency for distance calculation (http://django-haystack.readthedocs.org/en/v2.4.1/spatial.html) which should be avoidable if you plan to pass those queries directly to the search engine.

**Comment by jheld** [comment]
Hey @acdha , I haven't received any feedback on IRC or the google group.

I have a couple more specific questions regarding what you mentioned above. Would you be able to field them or help me find out who might know? I do appreciate what you've done so far. It has been by far the most help in the haystack community.
