### ISSUE TITLE
AWS ElasticSearch support

### ISSUE THREAD

**Issue by jheld** [django-haystack/django-haystack#1314]
I  see that https://github.com/pbs/haystack-cloudsearch has support for AWS searching credentials (secret and access keys/tokens), but I was curious if Haystack also by default did? I need this for my deployment to AWS so that django can talk to the elasticsearch node.

**Comment by acdha** [comment]
This just came up in #1303 – Haystack doesn't include anything standard since only a few of our users would need it but that seems like a great idea for a related application which could handle the configuration aspects.

**Comment by jheld** [comment]
How would you feel about adding in a new param to the haystack configuration such that you can pass in an optional backend_connection and set self.conn to that, instead of creating a whole new (in my case) Elasticsearch instance? My use case is such that I use the Elasticsearch init for AWS and those params are a bit different than what you guys use.

I'd rather just subclass your ElasticsearchSearchBackend, but at the moment, I don't know where/how your loading works to make that even possible. That's why I suggest including a defaulted to None parameter so I could still use haystack, instead of managing everything with elasticsearch(-py) directly.

If you know about subclassing the backend, for at least my short term I'd rather do that.

**Comment by acdha** [comment]
@jheld I think that would be preferable, and I'm definitely receptive to patches which would make customization easier. You should be able to do something like create a custom backend in your project starting as simply as something like 

```python
from haystack.backends.elasticsearch_backend import ElasticSearchBackend

class AWSElasticSearchBackend(ElasticSearchBackend):
    pass
```

and having your settings file use `'ENGINE': 'my_project.my_search_backend.AWSElasticSearchBackend'`. I use that approach with a custom Solr backend which adds partial (enough for my apps) support for Solr's document clustering if you want a more complicated example: https://gist.github.com/acdha/3750774. Note that you shouldn't need to customize things anywhere near as much since you're not changing the way queries are created or how the results are structured as my example does. I'm assuming most of what you'd be doing would just be changing `__init__` in https://github.com/django-haystack/django-haystack/blob/master/haystack/backends/elasticsearch_backend.py#L112 and perhaps we could make that easier by moving that to a separate `open_connection` method which your code could completely override.

**Comment by acdha** [comment]
(edited comment to correctly include the need to subclass the Engine so it uses the custom Backend – the default Query class should be fine)

**Comment by jheld** [comment]
Thanks for the suggestion and example customization code. I had read about creating new backends, but it hadn't occurred to me that a simple subclass would be good enough for that approach (or appropriate).

Yeah, I think an open_connection method would be interesting, but we'd have to ensure that the API/workflow adjusted well enough to look good with it -- due to it being in the init. I'd hope most developers don't muck with the backend in this way, but if they did, it would have to be a slightly breaking change in that way.

I'll try with the subclass first and see how I feel about making a real fork of the project with a working PR.

**Comment by acdha** [comment]
Thanks – one of my long-term goals is to simplify subclassing so this kind of tweak is easier. It'd be really nice if there was a PyPI project for something like Haystack + AWS ES which didn't need much code beyond what it takes to discover the search engine endpoint.

**Comment by SteveByerly** [comment]
Moving discussion/decision to #1406
