### ISSUE TITLE
Pypi release

### ISSUE THREAD

**Issue by WimCrols** [django-haystack/django-haystack#1381]
Hi,

This is not an issue, but I wondered if it is possible to make a pypi release of master. Since it is such a long time since the last release if we are now using a git hash to pull in a recent version, and this is quite slow.

Thank you,
Wim

**Comment by claudep** [comment]
There is a pre release on PyPi, https://pypi.python.org/pypi/django-haystack/2.5.dev1
Just set the --pre flag when installing with pip.

**Comment by Duologic** [comment]
Hi Claude

That doesn't really work in a standard environment, we can't make an exception for this one  dependency.

Is it really much effort to push a new version? We would really appreciate it at VikingCo.

Thanks

**Comment by acdha** [comment]
@Duologic I've been holding off on a new release because I haven't had time to do as much testing as I'd like and I was hoping to land the ES 2.0 branch for 2.5. If you code your version dependency *exactly* – e.g. `django-haystack==2.5.dev1` – pip will install a prerelease version as well.

Please let me know how the current code is working for you – my time has been pulled away at work this year but I'd like to pick things up more again.

**Comment by Duologic** [comment]
@WimCrols Can you try it out maybe? :+1:

**Comment by pembo13** [comment]
For one, this fixes the issue of the model not being found in the search results.

**Comment by SteveByerly** [comment]
@WimCrols there has been a release of master since your question: 2.5.dev2 is the latest.
Install with the pinned version as: django-haystack==2.5.dev2

**Comment by WimCrols** [comment]
Seems to work, tnx!

**Comment by acdha** [comment]
As of a couple seconds ago, 2.5.0 is on PyPI
