### ISSUE TITLE
UnicodeDecodeError while preparing object for update

### ISSUE THREAD

**Issue by savalou** [django-haystack/django-haystack#1382]
* [ x] Tested with the latest Haystack release
* [ ] Tested with the current Haystack master branch

## Actual behavior
Why is this error thrown for the SOLR backend at lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 56, in update?
Since the code is catching this exception, it seems like a known case. Am I missing something, can't Solr take non-ascii text?
## Steps to reproduce the behaviour

1. Index a file with some non-ascii text, like maybe devanagari characters: हिन्दी

## Configuration

* Operating system version: Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-74-generic x86_64)
* Search engine version: Solr 6.0.0
* Python version: 2.7
* Django version: 1.9.7
* Haystack version: 2.5.dev1

**Comment by acdha** [comment]
This sounds like your code is passing in a bytestring rather than a Unicode instance. I've been using haystack for years with non-ASCII text so I'd recommend starting by checking all of your code to make sure it decodes into Unicode strings as necessary. If you still have a problem, please provide the code and data needed to reproduce the failure.

**Comment by savalou** [comment]
Hi, yeah, you'e right. I was planning to come and update the thread. I was reading a file and converting the contents to string. As a Python newbie I have to say, I find the whole difference between '' and u'' very strange, but let's not go there.
