### ISSUE TITLE
There is no changelog since version 2.6.0

### ISSUE THREAD

**Issue by do3cc** [django-haystack/django-haystack#1600]
## Expected behaviour

I want to update haystack by at least one minor version. I am fully prepared to perform any necessary changes to prevent errors (especially silent ones)

## Actual behaviour

The changelogs are only maintained until version 2.6.0 (I went from 2.6.1 to 2.8.1)

It seems that the changelog was generated automatically but now isn't any more.

**Comment by acdha** [comment]
Yes - the automatic change log basically duplicates what you have on the stock GitHub releases view and it had maintenance issues with commit formatting and especially pull requests.

If you’d like to contribute a high level summary that’d be great but otherwise I’m inclined to replace the file with a link to the releases page.

**Comment by craigds** [comment]
https://github.com/django-haystack/django-haystack/releases doesn't have anything since 2.6.0 either though. are there upgrade notes somewhere else?

**Comment by craigds** [comment]
(I don't think a full changelog is very useful either; there are git logs for that; but a list of breaking changes is pretty important.)

**Comment by int-ua** [comment]
Just compare number of URLs opened trying to find out which version is the last to work with Django 1.8 (I have a massive project that I need a search on but don't have resources to update all the functionality to Django 1.11 because some modules are no longer maintained) for django-haystack and for django-import-export. Start with googling "module-name changelog".

**Comment by acdha** [comment]
I updated the release page to add releases for the tags so GitHub won't require you to click to see them. As always, Haystack is a volunteer project with no corporate backing and anyone who would like to help with a changelog, release notes, etc. would be helping the community.
