### ISSUE TITLE
Support for facet.pivot?

### ISSUE THREAD

**Issue by adambyer** [django-haystack/django-haystack#1766]
Is `facet.pivot` supported? https://solr.apache.org/guide/8_6/faceting.html#pivot-decision-tree-faceting

Thanks.

**Comment by acdha** [comment]
Not directly. Haystack has a constant challenge of balancing functionality which isn't supported by all of the backends or has significant differences between how different backends implement it.

I believe you can pass that value in directly and get it back from the raw response. It's been a while but I used that approach to support Solr's Collapse & Expand mechanism years back. I'm not sure whether you still need a custom SearchQuerySet to add the extra facet parameter but here's how I used a custom result processor to get arbitrary values back out:

https://gist.github.com/acdha/0a66ca23984bc8d607936fecd9c29941#file-collapsed-py-L63-L75

The other question is whether you actually want to do this. If your goal is simply to run a facet query without otherwise getting a full SQS you can get the pysolr instance from the `conn` property of the backend, which is accessible from any SQS instance as `.query.backend.conn`. I often prefer that to trying to hammer something into the SQS model if that's not an appropriate fit, and you could have a custom SQS subclass method which uses that to just return that portion of the response if that makes sense.

**Comment by adambyer** [comment]
Thanks @acdha!
