### ISSUE TITLE
Filtering (or excluding) on an empty list leads to bad query (SOLR exception)

### ISSUE THREAD

**Issue by orokusaki** [django-haystack/django-haystack#358]
Using ``SearchQuerySet``, here's an example:

    sqs.filter(foo__in=[])  # Empty list

The exception:

    org.apache.lucene.queryParser.ParseException: Cannot parse '((blabla AND ()[...rest omitted]': Encountered " ")" ") "" at line 1, column 14.

**Comment by jrhoads** [comment]
Is this still an issue 4 years and a couple versions later?

**Comment by acdha** [comment]
@jrhoads Apparently so – if you wanted to contribute a pull request, https://github.com/django-haystack/django-haystack/blob/6b61dc0b4c002cf97e6aa96f0e6308513040d060/haystack/backends/solr_backend.py#L579-L584 is the relevant place and it might be as simple as something like this:

```if not prepared_value:
    query_frag = '!*:*'
else:
    …
```

plus a test of some sort – based on https://github.com/django-haystack/django-haystack/blob/6b61dc0b4c002cf97e6aa96f0e6308513040d060/haystack/backends/__init__.py#L697-L701 we can't just return an empty value because that behaviour matches everything.

**Comment by boulderdave** [comment]
anybody heard if anybody has put in a patch for Elasticsearch?  Pretty surprising this is an issue - pretty common bug I would think..

**Comment by boulderdave** [comment]
Created PR for Elasticsearch for anybody needing it: https://github.com/django-haystack/django-haystack/pull/1335
