### ISSUE TITLE
Breaks when primary keys aren't strings or integers

### ISSUE THREAD

**Issue by ipmb** [django-haystack/django-haystack#399]
Lookups break with primary keys that aren't strings or integers (`uuid.UUID` objects as provided by [django-uuidfield](https://github.com/lincolnloop/django-uuidfield) for example).

Rather than assuming the `pk` is a string or integer, could the query force keys in the result of the `in_buik` lookup to unicode for the lookup? This way, instead of guessing the type of the `pk` you would just compare their unicode representations.

**Comment by seocam** [comment]
I believe we ran into the same issue. We had a model using integer fields and now we are using UUID. The result was that we have a DB with mixed pk (int and str). 

The problem is that the pk is a CharField but as haystack can do the conversion to int it just assumes that the field is an integer an fails to get the model data.

I think that just using the `get_prep_value` from Django would fix the issue. Here is an example:
https://gist.github.com/seocam/08da6ecf0e7cad061066a88593131010/revisions

**Comment by Brobin** [comment]
Does anyone have an example of an `HAYSTACK_IDENTIFIER_METHOD`? Or is the best way to use an integer as the primary key and just let the uuid be a separate unique identifier?

**Comment by acdha** [comment]
@Brobin I recently added a bit more to the test suite: https://github.com/django-haystack/django-haystack/commit/176bc54c2c439044ae427e6a30707cf4d74336e8

**Comment by Brobin** [comment]
Cool, thanks. I ended up just having an `id` and a `uuid` so haystack could use the `id` for indexing and I could use the `uuid` for forward facing urls etc.

**Comment by acdha** [comment]
@y2kbadbug haystack should support UUID keys and should be further customizable using the get_identifier mechanism. 

It’s also a completely volunteer project with no corporate support so something not being implemented usually means only that nobody values it enough to contribute code / documentation. If there’s something which would benefit your work please consider contributing it.
